//! `ore.toml` package manifest handling.
//!
//! ore is the Wolframite package manager. Each package has an `ore.toml`
//! manifest describing its name, version, and entry point. The format is a
//! deliberately small subset of TOML:
//!
//! ```toml
//! [package]
//! name = "hello"
//! version = "Dev (unstable)"
//! entry = "src/main.wfr"
//! ```
//!
//! Unknown sections and keys are ignored so future fields (dependencies,
//! authors, ...) can be added without breaking old parsers.

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const Manifest = struct {
    name: []const u8 = "unnamed",
    version: []const u8 = "Dev (unstable)",
    /// Source file compiled by `ore build` / `ore run` when no file is given.
    entry: []const u8 = "src/main.wfr",

    /// Parse a manifest from text. Values are duplicated into `allocator`.
    pub fn parse(allocator: Allocator, text: []const u8) !Manifest {
        var self = Manifest{};
        var in_package = false;

        var lines = std.mem.splitScalar(u8, text, '\n');
        while (lines.next()) |raw_line| {
            const line = std.mem.trim(u8, raw_line, " \t\r");
            if (line.len == 0 or line[0] == '#') continue;

            if (line[0] == '[') {
                in_package = std.mem.eql(u8, line, "[package]");
                continue;
            }
            if (!in_package) continue;

            const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
            const key = std.mem.trim(u8, line[0..eq], " \t");
            const raw_value = std.mem.trim(u8, line[eq + 1 ..], " \t");
            const value = unquote(raw_value);

            if (std.mem.eql(u8, key, "name")) {
                self.name = try allocator.dupe(u8, value);
            } else if (std.mem.eql(u8, key, "version")) {
                self.version = try allocator.dupe(u8, value);
            } else if (std.mem.eql(u8, key, "entry")) {
                self.entry = try allocator.dupe(u8, value);
            }
        }
        return self;
    }

    /// Serialize the manifest back to `ore.toml` text.
    pub fn render(self: *const Manifest, allocator: Allocator) ![]u8 {
        return std.fmt.allocPrint(allocator,
            \\# ore.toml - Wolframite package manifest
            \\# Generated by `ore init`.
            \\[package]
            \\name = "{s}"
            \\version = "{s}"
            \\entry = "{s}"
            \\
        , .{ self.name, self.version, self.entry });
    }
};

fn unquote(value: []const u8) []const u8 {
    if (value.len >= 2 and (value[0] == '"' and value[value.len - 1] == '"')) {
        return value[1 .. value.len - 1];
    }
    if (value.len >= 2 and (value[0] == '\'' and value[value.len - 1] == '\'')) {
        return value[1 .. value.len - 1];
    }
    return value;
}

// ============================================================================
// Tests
// ============================================================================

test "manifest: parse full document" {
    const manifest = try Manifest.parse(std.testing.allocator,
        \\# comment
        \\[package]
        \\name = "hello"
        \\version = "0.2.0"
        \\entry = "src/main.wfr"
        \\
    );
    defer std.testing.allocator.free(manifest.name);
    defer std.testing.allocator.free(manifest.version);
    defer std.testing.allocator.free(manifest.entry);

    try std.testing.expectEqualStrings("hello", manifest.name);
    try std.testing.expectEqualStrings("0.2.0", manifest.version);
    try std.testing.expectEqualStrings("src/main.wfr", manifest.entry);
}

test "manifest: missing fields fall back to defaults" {
    const manifest = try Manifest.parse(std.testing.allocator, "[package]\nname = \"x\"\n");
    try std.testing.expectEqualStrings("x", manifest.name);
    try std.testing.expectEqualStrings("Dev (unstable)", manifest.version);
    try std.testing.expectEqualStrings("src/main.wfr", manifest.entry);
}

test "manifest: ignores unknown sections and keys" {
    const manifest = try Manifest.parse(std.testing.allocator,
        \\[build]
        \\release = true
        \\[package]
        \\name = "demo"
        \\entry = "app.wfr"
        \\future-field = "whatever"
        \\
    );
    try std.testing.expectEqualStrings("demo", manifest.name);
    try std.testing.expectEqualStrings("app.wfr", manifest.entry);
}

test "manifest: render round-trips" {
    var manifest = try Manifest.parse(std.testing.allocator,
        \\[package]
        \\name = "pkg"
        \\version = "1.2.3"
        \\entry = "lib/main.wfr"
        \\
    );
    defer std.testing.allocator.free(manifest.name);
    defer std.testing.allocator.free(manifest.version);
    defer std.testing.allocator.free(manifest.entry);

    const text = try manifest.render(std.testing.allocator);
    defer std.testing.allocator.free(text);

    const reparsed = try Manifest.parse(std.testing.allocator, text);
    defer std.testing.allocator.free(reparsed.name);
    defer std.testing.allocator.free(reparsed.version);
    defer std.testing.allocator.free(reparsed.entry);

    try std.testing.expectEqualStrings(manifest.name, reparsed.name);
    try std.testing.expectEqualStrings(manifest.version, reparsed.version);
    try std.testing.expectEqualStrings(manifest.entry, reparsed.entry);
}
